name: tdlm
channels:
  - conda-forge
  - defaults
dependencies:
  - python>=3.8
  - numpy>=1.20.0
  - pandas>=1.3.0
  - tqdm>=4.60.0
  - matplotlib>=3.5.0  # for plotting examples
  - scipy>=1.7.0       # additional scientific computing
  - pip
  - pip:
    - black
    - flake8
    - pytest
    - pytest-cov
