site_name: PyTDLM
site_url: https://rtdlm.github.io/PyTDLM/
repo_url: https://github.com/RTDLM/PyTDLM
repo_name: PyTDLM
theme:
  logo: assets/logo.png
  favicon: assets/logo.png
  icon:
    repo: fontawesome/brands/github
  name: material
  palette:
    primary: deep purple
  features:
    - navigation.tabs
    - navigation.tabs.sticky
plugins:
  - mkdocstrings
markdown_extensions:
  - admonition
  - codehilite
  - toc:
      permalink: true
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
nav:
  - Home: index.md
  - Quick start: start.md
  - Tutorial: tutorial.md
  - News: news.md
  - R Package: https://rtdlm.github.io/TDLM/


