name: Test Examples

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  test-basic-usage:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    
    - name: Install package and dependencies with pip
      run: |
        python -m pip install --upgrade pip
        pip install -e .
        pip install matplotlib  # Needed for example
    
    - name: Test basic usage example with pip
      run: |
        cd docs/examples
        python basic_usage.py
    
    - name: Test with conda environment
      uses: conda-incubator/setup-miniconda@v2
      with:
        auto-update-conda: true
        python-version: '3.9'
        environment-file: environment.yml
        activate-environment: tdlm
    
    - name: Test basic usage with conda
      shell: bash -l {0}
      run: |
        conda activate tdlm
        conda install matplotlib
        # Install the pre-built conda package
        PACKAGE_PATH=$(find conda-dist -name "*.tar.bz2" | head -1)
        echo "Installing package: $PACKAGE_PATH"
        conda install $PACKAGE_PATH -c conda-forge -y
        cd docs/examples
        python basic_usage.py
